### ISSUE TITLE
Surprising behavior because of ExceptionGroup

### ISSUE THREAD

**Issue by Kinnay** [agronholm/anyio#141] opened 2020-08-02 20:27 UTC
Hi,

Imagine the following code:

```python
import anyio

async def task1():
    # This task raises an exception. Oops.
    raise ValueError

async def task2():
    raise ValueError # Another bug

async def run_tasks():
    async with anyio.create_task_group() as tg:
        await tg.spawn(task1)
        await tg.spawn(task2)

async def main():
    try:
        await run_tasks()
    except Exception:
        # Catch any exception that might occur in a child task
        print("Something went wrong")

anyio.run(main)
```

The `ValueErrors` aren't caught by `main`, because the task group merges them into an `ExceptionGroup`, which is not a subclass of `Exception`. Perhaps this is the intended behavior, but it did lead to a surprise on my end. The tasks only raise `ValueError` after all, which would normally be caught by the try-except statement.

To provide context: I'm writing a server and want to make sure that exceptions that are raised by a single connection do not affect the other connections. Whenever an exception occurs, the server should only close the connection that caused the exception, but keep serving other connections.

In my case it was even more complicated:

```python
import anyio

async def task1():
    # This task raises an exception. Oops.
    raise ValueError

async def task2():
    await anyio.sleep(1) # No bugs here

async def run_tasks():
    try:
        async with anyio.create_task_group() as tg:
            await tg.spawn(task1)
            await tg.spawn(task2)
    except Exception:
        # Catch any exception that might occur in a child task
        print("Something went wrong")

async def main():
    async with anyio.create_task_group() as tg:
        await tg.spawn(run_tasks)
        await tg.cancel_scope.cancel()

anyio.run(main)
```

This script does not even terminate with an `ExceptionGroup`. It terminates with a `ValueError`, even though the code that raises the `ValueError` is within the try-except block. I was really confused when this happened. It felt like the `ValueError` was leaking through the try-except statement somehow.

With a bit of debugging, I eventually figured out what's happening. When `main` cancels `run_tasks` it implicitly raises a `CancelledError` in `task2`. The task group in `run_tasks` merges both exceptions into an `ExceptionGroup`. Because `ExceptionGroup` is not a subclass of `Exception` it is not caught by the try-except statement. When the `ExceptionGroup` leaves the task group in `main`, the `CancelledError` is filtered away. Only the `ValueError` remains.

I don't want to catch `BaseException` here, because I don't want to catch exceptions like `CancelledError` or `KeyboardInterrupt`. I also can't catch `ExceptionGroup` here, for the same reason. Anyio's documentation does not seem to explain any way to extract a specific exception from an exception group, so I'm not sure how I should deal with this.

What do you think?

**Comment by agronholm** [comment] 2020-08-02 20:41
The title is a bit misleading – as you explained yourself, `ExceptionGroup` is a subclass of `BaseException`, not `Exception`. Catching `ExceptionGroup` will give you an opportunity to get to that `ValueError`. You can do so via the `ExceptionGroup.exceptions` attribute, and the fact that it's not documented is simply an oversight which I will correct momentarily.

> I don't want to catch BaseException here, because I don't want to catch exceptions like CancelledError or KeyboardInterrupt. I also can't catch ExceptionGroup here, for the same reason. Anyio's documentation does not seem to explain any way to extract a specific exception from an exception group, so I'm not sure how I should deal with this.

You can always reraise exceptions you don't intend to handle using a plain `raise` statement.

**Comment by Kinnay** [comment] 2020-08-03 09:32
> as you explained yourself, `ExceptionGroup` is a subclass of `BaseException`, not `Exception`. Catching `ExceptionGroup` will give you an opportunity to get to that `ValueError`. You can do so via the `ExceptionGroup.exceptions` attribute

I discovered that after debugging more than an hour. In my opinion, this behavior is really confusing (at least, for newcomers like me). Since the `ValueError` is raised within the try-except block it shouldn't ever reach `main`.

I would have to catch both `Exception` and `ExceptionGroup` here, and remove anything that is a subclass of `Exception` from the exception group manually, right? It feels a bit error prone and it's easy to forget about `ExceptionGroup` if you only want to catch a specific exception. I'm not sure if there is any way to avoid that though.  If I think about it, it makes sense that `ExceptionGroup` is a subclass of `BaseException`, because it shouldn't be caught if it contains a `CancelledError`. I suppose it's a limitation of the python language :confused:.

**Comment by agronholm** [comment] 2020-08-03 10:24
Trio has the same problem because no programming language I know of has a concept of an exception group. Yet this is better than doing what asyncio does which is raising the first exception and ignoring the rest. There was supposed to be a new PEP for integrating this into the Python language but that work has not really taken off yet.

Would it help if I added something like [MultiError.catch()](https://trio.readthedocs.io/en/v0.16.0/reference-core.html#trio.MultiError.catch) from trio?

**Comment by agronholm** [comment] 2020-08-03 10:30
Another question: if two exceptions were really raised from the task group, would you really have wanted to only catch `ValueError`? Where would the other exception go then?

**Comment by Kinnay** [comment] 2020-08-03 13:29
> Would it help if I added something like [MultiError.catch()](https://trio.readthedocs.io/en/v0.16.0/reference-core.html#trio.MultiError.catch) from trio?

Maybe. It does seem useful to me. Handling the exceptions in a separate function and doing the `isinstance` manually checks feels a bit cumbersome though :thinking: .

> Another question: if two exceptions were really raised from the task group, would you really have wanted to only catch `ValueError`? Where would the other exception go then?

In my case, I don't care. I just wanted a generic catch-all that logs a warning and ignores the exceptions.

Seems like this has been discussed in depth on trio's repo already ([issue](https://github.com/python-trio/trio/issues/611)). Someone suggested that you could use different types of MultiError ([comment](https://github.com/python-trio/trio/issues/611#issuecomment-541598694)):

> Taking this a little further, you could make the multi-error exception be:
>   * Cancelled (derived from BaseException), if any of them are Cancelled
>   * else BaseMultiError (derived from BaseException), if any of them is outside of Exception (e.g. KeyboardInterrupt)
>   * else MultiError (derived from Exception)

At first glance, this feels like it could work. I don't need (or want) to handle the exception if the task is cancelled or `KeyboardInterrupt` is raised. And in other cases, MultiError would be derived from `Exception`, and it would be caught by my try-except statement like I intended. I'm really new to async programming though, so maybe I'm missing a case where this would fail.

I also saw that someone ran into the same issue as I did ([here](https://github.com/python-trio/trio/issues/800)):
> What made it so hard to debug is that the final exception trace has no mention of MultiError, only the bare exception. Which made it seem like the `except` clause was mysteriously ignored.

This is precisely the reason I was so confused when `main` raised a `ValueError` in my second code example.

**Comment by agronholm** [comment] 2020-08-03 13:32
> This is precisely the reason I was so confused when main raised a ValueError in my second code example.

Wait, do you mean there was no second traceback there? Just one exception inside the exception group?

**Comment by Kinnay** [comment] 2020-08-03 13:34
Yes. Here's the output. It only raises `ValueError`:
```
yannik@yannik:~/Desktop$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    anyio.run(main)
  File "/home/yannik/.local/lib/python3.6/site-packages/anyio/__init__.py", line 72, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/home/yannik/.local/lib/python3.6/site-packages/anyio/_backends/_asyncio.py", line 114, in run
    raise exception
  File "/home/yannik/.local/lib/python3.6/site-packages/anyio/_backends/_asyncio.py", line 76, in wrapper
    retval = await func(*args)
  File "test.py", line 22, in main
    await tg.cancel_scope.cancel()
  File "/home/yannik/.local/lib/python3.6/site-packages/anyio/_backends/_asyncio.py", line 392, in __aexit__
    raise exceptions[0]
  File "/home/yannik/.local/lib/python3.6/site-packages/anyio/_backends/_asyncio.py", line 415, in _run_wrapped_task
    await func(*args)
  File "test.py", line 5, in task1
    raise ValueError
ValueError
yannik@yannik:~/Desktop$
```

**Comment by agronholm** [comment] 2020-08-03 13:41
Well, here's the trio version which has almost identical behavior:
```python3
import trio


async def task1():
    # This task raises an exception. Oops.
    raise ValueError

async def task2():
    await trio.sleep(1) # No bugs here

async def run_tasks():
    try:
        async with trio.open_nursery() as nursery:
            nursery.start_soon(task1)
            nursery.start_soon(task2)
    except trio.MultiError as err:
        print('got multierror with exceptions:', err.exceptions)
    except Exception:
        # Catch any exception that might occur in a child task
        print("Something went wrong")

async def main():
    async with trio.open_nursery() as nursery:
        nursery.start_soon(run_tasks)
        nursery.cancel_scope.cancel()

trio.run(main)
```

**Comment by agronholm** [comment] 2020-08-03 13:47
Ah, the problem is that `cancel()` you are calling in `main()`. Remove that and the snippet works as expected.

**Comment by agronholm** [comment] 2020-08-05 10:00
Anyway, what needs to be done to close this issue? Implement the same utility functions as in `trio.MultiError`?

**Comment by Kinnay** [comment] 2020-08-05 14:05
You can close it if you like. I implemented my own work around based on the `exceptions` attribute that you mentioned:

```python
try:
    ...
except anyio.exceptions.ExceptionGroup as e:
    filtered = []
    for exc in e.exceptions:
        if isinstance(exc, Exception):
            logger.error("An exception occurred", exc_info=exc)
        else:
            filtered.append(exc)
    if filtered:
        e.exceptions = filtered
        raise e
except Exception:
    logger.exception("An exception occurred")
```

It would be nice if you could update the documentation though. Right now `ExceptionGroup` seems to be gone from the documentation entirely?

**Comment by agronholm** [comment] 2020-08-05 14:18
> It would be nice if you could update the documentation though. Right now ExceptionGroup seems to be gone from the documentation entirely?

The exceptions were missing entirely from the documentation in v1.X which you are probably viewing right now (stable). Check out the `latest` in the docs viewer and you'll see it. I will add this in the docs and close the issue then.

**Comment by Kinnay** [comment] 2020-08-07 16:07
I discovered something weird. Here's a minimal example that reproduces it:
```python
import anyio

async def task():
	async with anyio.create_task_group() as tg:
		await tg.spawn(anyio.sleep, 1)
		await tg.cancel_scope.cancel()
		raise ValueError

async def main():
	async with anyio.create_task_group() as tg:
		await tg.cancel_scope.cancel()
		await task()
	
anyio.run(main)
```

With the trio backend, I get a `ValueError`, but with the asyncio and curio backends I get an infinite chain of exceptions until the recursion limit is reached.

**Comment by agronholm** [comment] 2020-08-07 17:18
Thanks, but would you mind reporting this as a separate issue (because it is)?

**Comment by Kinnay** [comment] 2020-08-07 17:37
Sure, sorry about that.

**Closed** 2020-08-08 08:12 UTC
