### ISSUE TITLE
Aiohttp fails, claiming it's not inside a task

### ISSUE THREAD

**Issue by martmists** [agronholm/anyio#48] opened 2019-04-02 15:49 UTC
code:
```py
    async def do_thing():
        ...
        async with fail_after(some_timeout):
            async with ClientSession() as session:
                async with session.get(url) as resp:
                    data = await resp.json()
```
error:
```
Traceback (most recent call last):
  File "my_file.py", line 138, in do_thing
    async with session.get(url) as resp:
  File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 855, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 321, in _request
    with timer:
  File "/usr/lib/python3.7/site-packages/aiohttp/helpers.py", line 658, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```

**Comment by smurfix** [comment] 2019-04-02 15:56
aiohttp is doing somewhat-incompatible things with async functions and their decorators. There doesn't seem to be an easy workaround.
My recommendation: If you can, use asks; the next version, not yet released, will run with anyio.

**Comment by agronholm** [comment] 2019-04-03 05:49
@martmists can you provide a minimal but complete running example?

**Comment by martmists** [comment] 2019-04-03 07:12
```py
async def test_aiohttp():
    async with ClientSession() as session :
        async with session.get("https://google.com") as response:
            await response.read()

anyio.run(test_aiohttp, backed="curio")
```

**Comment by smurfix** [comment] 2019-04-03 07:32
aiohttp does not work with any non-asyncio backend. Not a bug.

**Comment by agronholm** [comment] 2019-04-03 07:32
As he said. Closing.

**Closed by agronholm** 2019-04-03 07:32 UTC
