### ISSUE TITLE
Anyio run with pytest but wasn't asked for it

### ISSUE THREAD

**Issue by buhtz** [agronholm/anyio#667] opened 2024-01-11 08:28 UTC
In short: It seems `anyio` do work without being asked for when someone runs `pytest` and it doesn't matter if the related project to import `anyio` or configured it.

Expected behavior: Don't run `anyio` when the related project (tested by `pytest`) doesn't use it.

I discovered that while running `pytest` on one of my projects a folder `.hypothesis` appears. But I don'
t use `hypothesis` in this or any other project but I assume it is installed as a dependency of another foreign package.

I opened an [Issue at `hypothesis`](https://github.com/HypothesisWorks/hypothesis/issues/3836) and they encouraged me to look at the other pytest plugins running on my machine. There is only `anyio`.

Blocking the plugin is a workaround but IMHO not a solution.

**Comment by smurfix** [comment] 2024-01-11 08:57
So what's the actual bug? The fact that a plugin does some work when it's installed, even if not explicitly called to do so, might be improvable, but when there's nothing that actually breaks …?

**Comment by agronholm** [comment] 2024-01-11 09:00
Yeah, I'm also wondering what work the plugin allegedly does. I don't like that you wiped away the form fields in an edit; they're there to prevent frivolous bug reports like this seems to be.

**Comment by buhtz** [comment] 2024-01-11 09:19
The plugin does create files in project folders. It does some work that I don't know about. What do it does when I never called it?

**Comment by agronholm** [comment] 2024-01-11 09:20
The plugin has no functionality whatsoever that creates any files anywhere. Where is your proof?

**Comment by smurfix** [comment] 2024-01-11 10:25
In any case, according to the hypothesis bug linked above, yo can reproduce the problem by simply importing `hypothesis`. No anyio plugin required. Thus I'll close this issue.

**Closed by smurfix** 2024-01-11 10:25 UTC
Labels: bug

**Comment by saper** [comment] 2025-11-12 00:49
Maybe this should be solved by decoupling the plugin https://github.com/agronholm/anyio/discussions/1029
