### ISSUE TITLE
Run_sync (v3) raises `AsyncLibraryNotFoundError` for python3.6

### ISSUE THREAD

**Issue by mwakaba2** [agronholm/anyio#286] opened 2021-05-09 22:57 UTC
## Problem
The `AsyncLibraryNotFoundError` is getting raised for running a synchronous function in a worker thread in py3.6. 

For more context, [Jupyter Server #505](https://github.com/jupyter-server/jupyter_server/issues/505)

## How to reproduce
Python version: `Python 3.6.13 :: Anaconda, Inc.`

Confirm `AsyncLibraryNotFoundError` isn't raised for `anyio==2.2.0`.
```bash
$ pip install anyio==2.2.0
$ python test_run_sync.py
```

`AsyncLibraryNotFoundError` shows up for `anyio==3.0.1` in python3.6. I ran this in python3.7, and the error didn't show up. 
```bash
$ pip install anyio==3.0.1
$ python test_run_sync.py

Exception in callback WorkerThread.stop(<Task finishe...> result=None>)
handle: <Handle WorkerThread.stop(<Task finishe...> result=None>)>
Traceback (most recent call last):
  File "/Users/mwaka/opt/anaconda3/envs/jp_test_3.6/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Users/mwaka/opt/anaconda3/envs/jp_test_3.6/lib/python3.6/site-packages/anyio/_backends/_asyncio.py", line 708, in stop
    _threadpool_workers.get().discard(self)
  File "/Users/mwaka/opt/anaconda3/envs/jp_test_3.6/lib/python3.6/site-packages/anyio/lowlevel.py", line 113, in get
    return self._current_vars[self._name]
  File "/Users/mwaka/opt/anaconda3/envs/jp_test_3.6/lib/python3.6/site-packages/anyio/lowlevel.py", line 97, in _current_vars
    token = current_token()
  File "/Users/mwaka/opt/anaconda3/envs/jp_test_3.6/lib/python3.6/site-packages/anyio/lowlevel.py", line 54, in current_token
    return get_asynclib().current_token()
  File "/Users/mwaka/opt/anaconda3/envs/jp_test_3.6/lib/python3.6/site-packages/anyio/_core/_eventloop.py", line 109, in get_asynclib
    asynclib_name = sniffio.current_async_library()
  File "/Users/mwaka/opt/anaconda3/envs/jp_test_3.6/lib/python3.6/site-packages/sniffio/_impl.py", line 82, in current_async_library
    "unknown async library, or not in async context"
sniffio._impl.AsyncLibraryNotFoundError: unknown async library, or not in async context
```

The `test_run_sync.py` script: https://gist.github.com/mwakaba2/e76b0bc341bf17c97ff58cd4c672e4d4

**Comment by agronholm** [comment] 2021-05-10 11:59
Thanks, the repro script should speed up the investigation a lot!

**Comment by agronholm** [comment] 2021-05-10 13:00
For some reason, I cannot reproduce this in the test suite, even if I run the exact same code without any fixtures, and only that test.

**Comment by agronholm** [comment] 2021-05-10 13:14
I have an elegant fix for this but without a working regression test I'm hesitant to commit it.

**Comment by mwakaba2** [comment] 2021-05-10 16:12
@agronholm Thanks so much for the quick fix! 

In your PR, I see a test that checks for any exceptions in `run_sync`. Were you able to reproduce the exception before the fix?

**Closed** 2021-05-11 17:09 UTC
Labels: asyncio, bug
