### ISSUE TITLE
synchronous Event set

### ISSUE THREAD

**Issue by belm0** [agronholm/anyio#179] opened 2020-12-19 12:33 UTC
I'd like to use anyio for compatibility across asyncio and Trio, but async `Event.set()` (due to Curio) is a non-starter.  Event is a widely use primitive.  I'm guessing that an async `set()` would double the number of functions needing to be async in my program, and hence greatly increase the race conditions I'd need to ponder.  It's advised in "The Function Colour Myth" to keep async function percentage to a minimum.

It's not like I'm explicitly opting to not support Curio either, because my intended use case depends on Quart, which itself only supports asyncio and Trio.

It seems like there could just be a `synchronous_set()` method in the ABC, and Curio could raise NotImplementedError.  Isn't there already precedent with `FileStreamWrapper.send_eof()`?.

**Comment by agronholm** [comment] 2020-12-19 14:46
`FileStreamWrapper.send_eof()` is an oddity in the curio backend which could be replaced with two separate wrappers, one for stdin and one for stdout/stderr. Therefore it does not introduce any loss of functionality due to the `NotImplementedError` because the streams in `abc.Process` have been declared as either `ByteSendStream`s or `ByteReceiveStream`s, neither of which declares the `send_eof()` method.

I've heard this request before, and it puts me in a difficult position. I know people want it, but it would break the promise of being able to switch backends at will.

**Comment by smurfix** [comment] 2020-12-19 15:09
I feel your pain.

The problem is that async code doesn't live in a vacuum. Sometimes you need to interface with classic callback-oriented code. When *every* method in anyio's API requires an async call, you're stuck.

OK, not quite; there's `greenback`, or you can use a helper thread that reads a traditional queue and feeds the buffered data back into anyio by way of `run_async_from_thread`. However, both have some nontrivial overhead, not to mention a strong "come on there's gotta be some easier way to do this" stink.

The third way of course is to call `Event.set().__await__.__next__()` and punt if that doesn't raise `StopIteration` …

**Comment by agronholm** [comment] 2020-12-19 15:11
> Event.set().__await__.__next__() and punt if that doesn't raise StopIteration …

I recall I investigated this possibility on curio before and it was a non-starter. I can take another look and post my findings here.

**Comment by smurfix** [comment] 2020-12-19 15:34
> I recall I investigated this possibility on curio before and it was a non-starter. 

No, that doesn't work on curio, which is what my `punt if …` part was alluding to.

**Comment by agronholm** [comment] 2020-12-19 19:29
Could we possibly introduce an alternative `Event` which had a synchronous `set()` method and which on curio uses `concurrent.futures.Future`s?

**Comment by belm0** [comment] 2020-12-20 10:36
If it's possible to implement Event without async set on Curio, even if it's less efficient, it would be a win to do that and forgo Curio's native event entirely.

Otherwise every app using libraries implemented with anyio will have to bear the complexity burden due to a larger async surface area in API's.

I don't think an alternative Event is a good idea.  How does a middle library author decide which to use?  If he uses the current `Event` his API will be more complex (more async functions), and that complexity is passed on to dependees.  If he uses the alternative Event then ... what?  The library will be a tiny bit slower on Curio?  Who cares?

If it's a question of efficiency, consider that Trio is the slowest kid on the block and instead strives to have the best API-- and it pays off in minimizing the complexity of writing and maintaining a concurrent program.  I'll take that over the "fastest" async library any day.

**Comment by agronholm** [comment] 2020-12-20 11:26
> If it's possible to implement Event without async set on Curio, even if it's less efficient, it would be a win to do that and forgo Curio's native event entirely.

What do you propose exactly?

> I don't think an alternative Event is a good idea. How does a middle library author decide which to use? If he uses the current Event his API will be more complex (more async functions), and that complexity is passed on to dependees. If he uses the alternative Event then ... what? The library will be a tiny bit slower on Curio? Who cares?

There is the matter of `set()` being a coroutine function so in the strictest technical sense making that into a synchronous function might break things. To support `await`, we would have to return a dummy awaitable from the method, but if someone had been storing the coroutine object (even short term) and only awaiting on it later, the behavior will change. It's _probably_ not going to cause issues in practice, just pointing it out.

**Comment by smurfix** [comment] 2020-12-20 11:49
Curio delegates everything, including task wakeup, through its kernel. This means that you cannot just iterate the async `Event.set()` and expect that to work. However, all those kernel trap functions are sync (by definition). Thus it's fairly easy (but not at all portable across curio versions I would assume) to write a synchronous `set` workaround.

To prepare, in async land you need to acquire a ref to the current kernel. `kernel = await curio.traps._get_kernel()`. This doesn't change so you can do it from within `anyio.run`.

Then, to set an event from sync code:
```
def sync_set(event):
    event._set = true
    n = len(event._waiting._tasks)
    kernel._traps["trap_sched_wake"](event._waiting, n)
```

Disclaimer: untested by from reading the code something like this should work.

**Comment by agronholm** [comment] 2020-12-28 11:52
Since I have pledged semver compliance in AnyIO, I see only two options here:

1. Add a new ABC for a sync-setting event
2. Modify the existing interface so `set()` is synchronous, and release AnyIO 3.0

Thoughts?

**Comment by smurfix** [comment] 2020-12-28 12:19
3. Modify the existing interface so `set` returns a no-op awaitable (which probably should emit a deprecation warning). Remove the compat workaround in anyio 3.0, which can otherwise wait until there's a more substantial change. 

Take that time to investigate whether we should teach any other interfaces to either not be async or have a sync variant; sending to a memory queue comes to mind.

**Comment by frederikaalund** [comment] 2020-12-28 14:13
Note that #168 implements option 1.

**Comment by agronholm** [comment] 2020-12-28 16:02
> Modify the existing interface so set returns a no-op awaitable (which probably should emit a deprecation warning). Remove the compat workaround in anyio 3.0, which can otherwise wait until there's a more substantial change.

The method was declared to be a coroutine method. Replacing it with something that acts immediately without `await` breaks the interface and requires a major version bump. I'd hate to do that just to fix this one issue, but if there are enough other breaking changes to warrant a 3.0, I can consider it.

**Comment by belm0** [comment] 2020-12-29 04:33
I can respect wanting to be strict about semantic versioning.

If going that route, the best thing is to accept it as a mis-design of the API and encourage everyone to get on 3.0.

Notably I hope that 3.0 does not have a remnant type called "UniversalEvent", and I hope that middle library authors don't need to fret between using anyio.Event vs. UniversalEvent (or trying to support both).    Use the API with synchronous set... any apps should be freezing their dependencies until things are sorted out.

**Comment by njsmith** [comment] 2020-12-29 04:47
`Event` is possibly the most obvious API with this issue, but it's hardly unique. There are tons of synchonization primitives where you might want this. Doing a separate major release for each of them seems like an awkward plan...

**Comment by belm0** [comment] 2020-12-29 07:32
So let's try to enumerate them.  I looked at everything with `async` qualifier in the docs, and the following look like candidates:
  * MemoryObjectReceiveStream.receive_nowait
  * MemoryObjectSendStream.send_nowait
  * Semaphore.release
  * Lock.release
  * Condition.notify / notify_all / release
  * CapacityLimiter. acquire_nowait / acquire_on_behalf_of_nowait / release / release_on_behalf_of / set_total_tokens
  * get_current_task, get_running_tasks
  * (Event.set)

**Comment by smurfix** [comment] 2020-12-29 07:57
Not to forget `Lock.acquire_nowait` and `Semaphore.acquire_nowait`.

Convincing curio to support a sync `Event.set` is hairy enough but possibly worth it as a much-needed corner case. Doing all of these is not something I'd recommend doing.

> The method was declared to be a coroutine method. Replacing it with something that acts immediately without await breaks the interface and requires a major version bump. 

OK, then let's turn the sequence of events around and teach 3.0 to return a no-op pseudo coroutine which emits a deprecation warning. That way, at least those 99.9% of users which *always* call `await Event.set()` directly don't need a flag day.

**Comment by agronholm** [comment] 2020-12-29 10:27
On curio, I'm thinking of using a socket pair to implement notifications. Any objections?

Also, if we're doing a 3.0, a solution to the design problem in #177 should be incorporated into it as well.

**Comment by smurfix** [comment] 2020-12-29 10:38
+1 on fixing #177.

A socket pair is no problem for the release / send_nowait / Event.set cases, but won't work for the other possible cases @belm0 has identified. TBH that's mostly-fine with me.

**Comment by agronholm** [comment] 2020-12-29 10:40
> A socket pair is no problem for the release / send_nowait / Event.set cases, but won't work for the other possible cases @belm0 has identified. TBH that's mostly-fine with me.

Explain please? Event is the lowest level synchronization primitive and all others can be rebuilt around it.

**Comment by belm0** [comment] 2020-12-29 10:41
> Not to forget Lock.acquire_nowait and Semaphore.acquire_nowait

These appear to be methods not present at all in anyio, which is different than the cases I enumerated, and has no API compatibility issue.

**Comment by agronholm** [comment] 2020-12-29 10:47
> These appear to be methods not present at all in anyio, which is a different case than what I enumerated, and has no API compatibility issue.

IIRC, one of the backends was lacking these methods so they weren't incorporated into AnyIO's API. If I rebuild the primitives based on `Event`, that will become possible.

**Comment by belm0** [comment] 2020-12-29 10:57
> Event is the lowest level synchronization primitive and all others can be rebuilt around it.

In Trio, I notice that all the synchronization classes (including Event) are built on ParkingLot (a.k.a. wait queue).  Is there any advantage to be learned?

**Comment by agronholm** [comment] 2020-12-29 10:59
> In Trio, I notice that all the synchronization classes (including Event) are built on ParkingLot (a.k.a. wait queue). Is there any advantage to be learned?

I'm not sure, but parking lots are a trio specific mechanism.

**Comment by njsmith** [comment] 2020-12-29 11:18
Parking lots really haven't turned out to be as useful as I expected.

Building everything on top of Event is tricky though, because you really
want to be able to respond immediately to cancellation, within the context
of the cancelling code. Waiting until the cancelled code wakes up is super
prone to race conditions.

This is possible at least in asyncio and trio; dunno about curio.

**Comment by smurfix** [comment] 2020-12-29 11:19
> Explain please? 

You can't build a sync try-lock or try-receive-stream operation with a socketpair because you'd need to get that scheduled before you can proceed.

> Event is the lowest level synchronization primitive and all others can be rebuilt around it.

Well, no. It's one primitive you can use to build all the others with. Trio's parking lot is another, a simple Lock would also work (as long as you can acquire and release from different tasks of course).

**Comment by belm0** [comment] 2020-12-29 11:44
one more currently-async method that will be in the controversial category:

  * CancelScope.cancel

**Comment by frederikaalund** [comment] 2020-12-29 12:11
A synchronous `Event.set` and `MemoryObjectSendStream.send_nowait` solves issue #167.

**Comment by agronholm** [comment] 2020-12-29 12:46
> You can't build a sync try-lock or try-receive-stream operation with a socketpair because you'd need to get the other end scheduled before you can proceed. (At least on curio, because these calls need to go through the kernel and its API doesn't have a sync way to talk to it.)

To get what scheduled? I'm thinking of sending a single byte to the other socket using the sync socket API and that could never block.

**Comment by smurfix** [comment] 2020-12-29 14:03
> I'm thinking of sending a single byte to the other socket using the sync socket API and that could never block.

I understood that part. This idea works with calls that don't return any data. A non-blocking receive or a try-lock does however return something (and/or needs to wait until the operation actually succeeded). Thus this mechanism doesn't work for all calls we might want to be non-blocking.

Ideally we'd teach curio to offer a sync kernel interface for such calls … any chance of that happening, @dabeaz ?

**Comment by agronholm** [comment] 2020-12-29 14:28
> I understood that part. This idea works with calls that don't return any data. A non-blocking receive or a try-lock does however return something (and/or needs to wait until the operation actually succeeded). Thus this mechanism doesn't work for all calls we might want to be non-blocking.

I don't think I'm understanding your reasoning. Can you give me an example of a method that would not work this way?

**Comment by smurfix** [comment] 2020-12-29 15:58
> Can you give me an example of a method that would not work this way?

Umm … I just did?

Given only an async implementation of a timeout-cancellable "receive" or "acquire lock" operation, which is what curio affords, I don't see how you could possibly achieve that from a sync job which can only send into the future but, lacking a time machine, has no way of reading the result.

**Comment by agronholm** [comment] 2020-12-29 16:26
I'm still not understanding.

Here's my PoC curio implementation of `Event`:
```python3
from concurrent.futures import Future

import curio.traps


class Event:
    def __init__(self):
        self._future = Future()

    def set(self) -> None:
        self._future.set_result(None)

    def is_set(self) -> bool:
        return self._future.done()

    async def wait(self):
        if not self._future.done():
            await curio.traps._future_wait(self._future)


async def waiter(event, tasknum):
    await event.wait()
    print('Received notification in task', tasknum)


async def main():
    event = Event()
    tasks = []
    for i in range(5):
        tasks.append(await curio.spawn(waiter, event, i + 1))

    print('Tasks spawned')
    await curio.sleep(0.5)
    print('Notifying')
    event.set()
    print('Waiting for tasks to complete')
    for task in tasks:
        await task.join()

curio.run(main)
```
My PoC curio `Lock` implementation based on this `Event`:
```python3
class Lock:
    def __init__(self):
        self._waiters = deque()
        self._acquired = False

    async def acquire(self) -> None:
        if self._acquired:
            event = Event()
            self._waiters.append(event)
            try:
                await event.wait()
            except BaseException:
                self._waiters.remove(event)
                raise
        else:
            self._acquired = True

    def release(self) -> None:
        if not self._acquired:
            raise RuntimeError('This lock has not been acquired')

        if self._waiters:
            self._waiters.popleft().set()
        else:
            self._acquired = False

    def locked(self) -> bool:
        return self._acquired


async def locker(lock, tasknum):
    await lock.acquire()
    print('Acquired lock in task', tasknum)
    await curio.sleep(0.5)
    lock.release()


async def main():
    lock = Lock()
    tasks = []
    for i in range(5):
        tasks.append(await curio.spawn(locker, lock, i + 1))

    print('Waiting for tasks to complete')
    for task in tasks:
        await task.join()

curio.run(main)
```

**Comment by belm0** [comment] 2020-12-30 02:16
Is there consensus that, at the least, all `nowait` functions should be sync for 3.0?

Also, remaining async functions that happen to have a sync implementation in Trio should include a `sleep(0)` checkpoint, per Trio API rules.

**Comment by agronholm** [comment] 2020-12-30 08:10
> Is there consensus that, at the least, all nowait functions should be sync for 3.0?

This is something I've done in a local branch now.

> Also, remaining async functions that happen to have a sync implementation in Trio should include a sleep(0) checkpoint, per Trio API rules.

I'll keep this in mind. I'll make a PR with all these changes.

**Comment by smurfix** [comment] 2020-12-30 10:05
@agronholm OK, when you implement these things yourself instead of using the Curio types, then this is obviously not much of a problem.

> Is there consensus that, at the least, all nowait functions should be sync for 3.0?

Yes, though I'd very much prefer for the sync replacement functions (i.e. `Event.set` and friends) to return a deprecation-warning awaitable until 4.0 (or possibly 3.1). While I could convert all my anyio code all at once, I'd very much prefer not to have to.

**Comment by agronholm** [comment] 2020-12-30 10:06
> Yes, though I'd very much prefer for the sync replacement functions (i.e. Event.set and friends) to return a deprecation-warning awaitable until 4.0 (or possibly 3.1). While I could convert all my anyio code all at once, I'd very much prefer not to have to.

Yeah, this is the plan.

**Comment by dabeaz** [comment] 2020-12-30 10:28
The Curio kernel will never support a synchronous interface because strict separation of async/sync environments is the whole foundation of the project's design.   You can't directly call C functions in the Linux kernel from Python either.  Yet, somehow we all manage.

**Comment by agronholm** [comment] 2020-12-30 10:33
If I at least had a way to get the current task from curio without `await`, that would solve *a lot* of problems with AnyIO. If AnyIO was always used to start the kernel, I could use activations to keep track of the current task but that's not possible when AnyIO code is invoked from an already running curio event loop.

**Comment by agronholm** [comment] 2020-12-30 10:53
> Is there consensus that, at the least, all nowait functions should be sync for 3.0?

@belm0 Related to my previous comment, do you have a suggestion on how to implement this for `CapacityLimiter`? It uses the current task object as the borrower, but how can we get the current task in a synchronous method on curio?

**Comment by dabeaz** [comment] 2020-12-30 11:46
Why is the current Curio task needed in synchronous code?

**Comment by agronholm** [comment] 2020-12-30 12:46
> Why is the current Curio task needed in synchronous code?

The `CapacityLimiter` synchronization primitive needs to ensure that the same task does not acquire the limiter twice. This needs to be checked also in the `acquire_nowait()` method which is a synchronous method in trio but coroutine method in AnyIO only because we cannot get the current task in curio by a synchronous function call. Even if this didn't cause an API discrepancy, it's unintuitive for a method whose name ends with `_nowait()` to require awaiting.

As to why we're changing these any of these methods to be synchronous is due to practical concerns: a lot of existing libraries have callback based functionality (synchronous) and to be able to integrate with them, a synchronous `Event.set()` is needed. This at least is fortunately possible to implement on curio.

**Comment by smurfix** [comment] 2020-12-30 12:51
> The Curio kernel will never support a synchronous interface

Curio doesn't exist in a vacuum. Sometimes you need to interface with code that uses sync callbacks. We can't just rewrite all libraries we're using to async callbacks and/or return-some-events (sans-IO) style. Yes, personally I'd like to, but time is limited and some employers take a dim view of people doing too much work on support code that'd run perfectly well as-is – if they'd only drop their stubborn insistence on using those annoying and limiting Structured Concurrency ideas. :-P

As such we need a minimum of features available to sync code. Set an event, queue a message, or release a capacity limiter are among the most-missed features. As @agronholm  described, anyio will do the first two by signalling through a socketpair if you force it to, though the additional overhead just for setting an event is strictly in the "I don't like that at all" category IMHO. (To say the least. The fact that a sync `Event.set` would be three lines of code, albeit with way too many private-member unders, doesn't help either.)

Anyway. We'd like to use a task ID for capacity limiters because it makes sense to key acquiring them to the current task, if only to catch double-acquire or double-release bugs, and we need to access it from sync code to release the resource from there. Yes we can add workarounds, like having the acquisition return a token you'd have to call to release the resource, but that introduces another chunk of incompatibility with the other async libraries.

**Comment by agronholm** [comment] 2020-12-30 12:57
> As such we need a minimum of features available to sync code. Set an event, queue a message, or release a capacity limiter are among the most-missed features. As @agronholm described, anyio will do the first two by signalling through a socketpair if you force it to, though the additional overhead just for setting an event is strictly in the "I don't like that at all" category IMHO. (To say the least. The fact that a sync Event.set would be three lines of code, albeit with way too many private-member unders, doesn't help either.)

Just a slight correction: The current PoC curio implementation of `Event` uses the `_future_wait` kernel trap, not a socket pair. It passes tests but if it causes other problems then I can easily change it.

A synchronous `Event.set()` gets us most of the things you mentioned, but not all.

**Comment by dabeaz** [comment] 2020-12-30 13:30
Curio already has `UniversalEvent` and `UniversalQueue` objects for coordinating with synchronous code. Use that.

**Comment by agronholm** [comment] 2020-12-30 13:38
The event class is not the problem here.

**Comment by dabeaz** [comment] 2020-12-30 14:23
Although I can appreciate the concern, I'm not adding synchronous functions to the Curio kernel.   So, you'll have to implement some solution using futures (or something else) or drop support for Curio.

**Comment by agronholm** [comment] 2020-12-30 15:40
Given that futures do not offer a solution for getting the current task in a synchronous function on the event loop thread, dropping support may indeed be the only way forward.

**Comment by agronholm** [comment] 2020-12-30 16:01
This is a duplicate of #167 but I'm not closing this issue since it has plenty of useful commentary.

**Comment by agronholm** [comment] 2020-12-30 16:04
I made a PR that only changes `Event.set()`, but I also have code here that reimplements the other primitives using `Event`. Now I have to make a decision: whether to skirt the semver rules and include this in 2.x, or to jump right into 3.0.

**Comment by belm0** [comment] 2020-12-30 22:12
> Sometimes you need to interface with code that uses sync callbacks.

This is only part of the rationale.  Equally or more important, the more async calls a program has, the more we need to reason about concurrency and what state may change across the call.  Due to the GIL, single-threaded concurrency with explicit context switch is Python's sweet spot.  Code between async calls is effectively an atomic section, and awareness of that leads to much simpler concurrent programs.  The async surface area of an API compounds and directly affects complexity of the final application as you go up the stack-- starting with curio, then anyio, then middle libraries using anyio, all the way to the application.

**Comment by belm0** [comment] 2020-12-30 22:18
> or drop support for Curio

We should at least ponder how many apps with a transitive anyio dependency actually use a Curio loop, and wether it's worth imposing a significant complexity burden on everyone else.

The way anyio is now, it's a low value to me because I'm interested in minimizing async functions in my API's and applications.  I'd rather roll my own asyncio + Trio abstraction ad hoc.

**Comment by agronholm** [comment] 2020-12-30 23:06
> We should at least ponder how many apps with a transitive anyio dependency actually use a Curio loop, and whether it's worth imposing a significant complexity burden on everyone else.

We have no way of knowing how many apps have been built for curio out there. That said, I looked up the PyPI download counts of each async library project for November to get some idea:

- curio: 2,803
- anyio: 15,723
- trio: 27,220

From the looks of it, curio doesn't seem all that popular (sorry, David!) so not many will cry bloody murder if AnyIO drops support. It's a shame, but it's been somewhat of a liability for a while.

**Comment by dabeaz** [comment] 2020-12-31 00:00
Curio is not a popularity project so whether or not people decide to use it is somewhat immaterial as far as I'm concerned.  That said, I still think it's smaller, faster, and far easier to reason about than the alternatives.  So, at least there's that.

**Comment by agronholm** [comment] 2021-01-04 19:25
Given #185, the decision has now been made to drop curio support. I will use this opportunity to convert several coroutine functions/methods in the API to synchronous to match trio's API as closely as possible. All this will happen in the v3.0 release. I plan to make at least one more release in the 2.x series before that though.

**Comment by agronholm** [comment] 2021-02-08 22:29
Now that the decision was made to not implement this in the 2.x series, but rather in 3.0 in which curio is no more, I take it we don't want the backwards dummy awaitable for backwards compatibility? The incompatible API changes will of course be documented in the changelog.

**Comment by agronholm** [comment] 2021-02-08 23:39
I've updated the PR with changes that make all of the synchronization primitives synchronous where possible. There are more changes to come, once I have the opportunity.

**Comment by smurfix** [comment] 2021-02-09 06:12
Actually I would prefer for them to return a dummy awaitable (can be a constant object, thus there is almost no overhead).

It was a royal PITA here to atomically update everything to work with 2.0. I'd like to avoid having to do that again; I'd go so far as to patch that kind of compatibility stuff into my local anyio package myself.

**Comment by agronholm** [comment] 2021-02-09 15:09
How am I going to retain backwards compatibility for methods like `MemoryObjectReceiveStream.receive_nowait()` which return meaningful values?

**Comment by smurfix** [comment] 2021-02-09 15:32
Umm … well, I'm not using any _nowait functions in my code. I didn't even know anyio had them.

Looking at the patch as it is so far, though, I can understand why you wouldn't want to trouble with that stuff. No matter, I can do it myself locally if necessary.

**Comment by smurfix** [comment] 2021-02-09 15:35
NB, any particular reason why you're not using `pytest.raises` as a context manager in `test_run_sync_from_unclaimed_thread`?

**Comment by agronholm** [comment] 2021-02-09 15:39
> NB, any particular reason why you're not using pytest.raises as a context manager in test_run_sync_from_unclaimed_thread?

Why would I do that?

**Comment by smurfix** [comment] 2021-02-09 15:58
Because the code gets more readable by doing so IMHO, and you *are* using it as a context manager on a one-liner, in the patch before that. (I'm talking about commit df35a74 in `test_threads.py`.)
So I just wondered whether there was a reason for calling it directly. If not, that's fine too. :-)

**Comment by agronholm** [comment] 2021-02-09 15:59
I only use it as a context manager when I have to (i.e. when calling coroutine functions).

**Comment by smurfix** [comment] 2021-02-09 15:59
OK, fair enough.

**Closed** 2021-02-22 13:22 UTC
Labels: duplicate
