### ISSUE TITLE
Cancelling `TaskGroup.start()` cancels `TaskGroup` itself (only for `asyncio` backend)

### ISSUE THREAD

**Issue by jonathanslenders** [agronholm/anyio#710] opened 2024-04-02 10:45 UTC
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

4.3.0

### Python version

3.11.6

### What happened?

Consider this snippet:

```python
from anyio import create_task_group, run, sleep_forever, move_on_after


async def in_task_group(task_status):
    await sleep_forever()


async def main():
    async with create_task_group() as tg:
        with move_on_after(1):
            await tg.start(in_task_group)

        print(tg.cancel_scope.cancel_called). # prints 'True'


run(main, backend='asyncio')
```

Here we spawn a task using `TaskGroup.start()` then we cancel the `.start()` call using `move_on_after`. It turns out this cancels the task group as a whole.

I'd expect this to cancel only that particular task.

For the `trio` backend, this works fine, and does not cancel the task group.

### How can we reproduce the bug?

(see snippet above)

**Comment by agronholm** [comment] 2024-04-02 10:47
Isn't this a duplicate of #685?

**Comment by jonathanslenders** [comment] 2024-04-02 10:52
It might be, I don't really understand whether or not it's exactly the same.

**Comment by agronholm** [comment] 2024-04-02 10:53
I think it probably at least stems from the same issue which I intend to fix for the next release.

**Comment by jonathanslenders** [comment] 2024-04-02 10:54
Thanks! That would be awesome. Feel free to close this or copy over the snippet as an additional test case if you prefer that.

**Closed** 2024-05-26 21:25 UTC
Labels: bug
