### ISSUE TITLE
SocketStream.receive_some() cancellation

### ISSUE THREAD

**Issue by mark9064** [agronholm/anyio#119] opened 2020-06-15 17:54 UTC
Recently I was debugging and I found that receive_some on SocketStream does not raise for cancellation in some circumstances.
From my testing, if the server closes the connection, receive_some will never cancel during subsequent calls.

I understand that upon receive_some returning b"" the user should handle the socket being closed and that this is definitely an odd corner case, but no cancellation here seems to be inconsistent. Is it supposed to be this way?

Example:

Client
```python
import anyio

ADDR = ""
PORT = 0
TIMEOUT = 1 # must be more than SLEEP_TIME in server

async def recv_test():
    stream = await anyio.connect_tcp(ADDR, PORT)
    async with anyio.move_on_after(TIMEOUT):
        while True:
            await stream.receive_some(4096)
    print("Cancelled!") # this will never print

anyio.run(recv_test, backend="trio")
```

Server
```python
import socket
import time

ADDR = ""
PORT = 0
SLEEP_TIME = 0.1 # must be less than TIMEOUT in client

def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind((ADDR, PORT))
    sock.listen()
    while True:
        conn, _ = sock.accept()
        time.sleep(SLEEP_TIME)
        conn.close()

main()
```

I have not tested any other stream receive methods.

**Comment by agronholm** [comment] 2020-06-16 06:36
If this is indeed the case then you have found a bug. I've recently fixed a bug on the curio backend which involved a similar situation: timeout on a receive did nothing. It had nothing to do with sockets per se, but rather the after effects of the host task being cancelled during `connect_tcp()`. This did not happen with the trio backend though, so I do wonder what's up here.

I'll give it a whirl and report back.

**Comment by agronholm** [comment] 2020-06-16 07:07
Interesting. The client script goes into a busy loop, consuming 100% CPU. Something is definitely off here.

**Comment by agronholm** [comment] 2020-06-16 07:10
Yeah, what was I thinking. Closing the connection results in receiving `""`, just as it would with plain sockets. Why do you expect a cancellation here?

**Comment by agronholm** [comment] 2020-06-16 08:07
Right – the timeout. I really need some time off :)

**Comment by agronholm** [comment] 2020-06-16 08:15
Ok – I've figured this out. The reason this happens is because the loop is actually never yielding control so that the timeout task could be run and cancel the task. Switching from `trio.lowlevel.checkpoint_if_cancelled()` to `trio.lowlevel.checkpoint()` fixes the problem.

**Comment by njsmith** [comment] 2020-06-16 08:19
Note that Trio pretty much assumes that `checkpoint_if_cancelled` and `cancel_shielded_checkpoint` are always used together in pairs to make up a complete checkpoint. The only reason they're provided as separate operations is for cases where you need to do them at slightly different times.

**Comment by agronholm** [comment] 2020-06-16 08:19
The problem exists on all backends though.

**Closed** 2020-06-16 08:52 UTC
Labels: asyncio, bug, curio, trio

**Comment by agronholm** [comment] 2020-06-16 09:44
Looks like the fix caused some tests to start failing, but only on asyncio and curio. I'm not sure if it just uncovered more existing problems or caused them.

**Comment by agronholm** [comment] 2020-06-16 10:20
The good news: the test failures were caused by flawed testing methodology.
The bad news: `wait_all_tasks_blocked()` now triggers on the checkpoint. Relying on `sleep()` in the test code doesn't feel like the right solution.

**Comment by agronholm** [comment] 2020-06-16 11:31
Ok, the issue should be sorted out now.

**Comment by mark9064** [comment] 2020-06-16 13:29
That was a quick turnaround! Thanks for looking in to it :smile:
