### ISSUE TITLE
Type incompleteness

### ISSUE THREAD

**Issue by tkukushkin** [agronholm/anyio#396] opened 2021-11-27 19:28 UTC
I am trying to use Pyright as type checker and getting errors like this:

```
error: Type of "start_soon" is partially unknown
    Type of "start_soon" is "(func: (*args: Any, **kwargs: Any) -> Coroutine[Unknown, Unknown, Unknown], *args: object, name: object | None = None) -> None" (reportUnknownMemberType)
```

I think, type-parameters for generic types must be explicitly stated (as `Any` or as `object` in some cases).

**Comment by agronholm** [comment] 2021-11-27 19:29
As part of the automated test suite, we run mypy against both the source code and test suite itself with strict mode enabled.

What code triggers this error with pyright?

**Comment by tkukushkin** [comment] 2021-11-27 19:33
Any code that uses task groups triggers this error in pyright strict mode.

```python
import anyio

async def foo():
    pass

async def main():
    async with anyio.create_task_group() as tg:
        tg.start_soon(foo)
```

**Comment by agronholm** [comment] 2021-11-27 19:35
> I think, type-parameters for generic types must be explicitly stated (as Any or as object in some cases).

Not according to PEP 484 which says that `Any` is assumed in the absence of explicit parameters. What specification did pyright implement if not PEP 484?

**Comment by tkukushkin** [comment] 2021-11-27 19:43
Pyright has more stringent requirements for py.typed libraries. I can't tell you why that is. You can read what pyright defines as "type complete" in [its documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#type-completeness).

**Comment by agronholm** [comment] 2021-11-27 19:48
My stance here is that I will not go beyond the requirements of PEP 484. As neither PyCharm or Mypy complain about this, I feel the issue is limited only to pyright and as such I will not change the code.

**Comment by tkukushkin** [comment] 2021-11-27 19:53
@msfterictraut maybe you can describe reasoning of such pyright behaviour?

**Comment by erictraut** [comment] 2021-11-27 22:30
Pyright distinguishes between an explicit `Any` and an implicit `Any` type. The latter is displayed as `Unknown` to distinguish it from the former.

In basic type checking mode, all forms of `Any` are treated the same, consistent with PEP 484's rules. However, pyright offers stricter type checking modes where uses of `Unknown` are flagged as an error. This is important because missing type annotations within a library (or any code in general) are typically a sign that they author hasn't yet gotten around to providing a type annotation. This is understandable given that many libraries are annotated incrementally over time. If the library author has included an explicit `Any` type annotation, it's clear that it's not an unintended omission. 

If you want your library to work with strict type checking modes in pyright, you should explicitly annotate your library's types, even parameters and type arguments that are meant to be `Any`.

All of the type stubs in typeshed follow this rule and include explicit `Any` annotations for the same reason.

For more details about expectations for "py.typed" libraries, please refer to [this document](https://github.com/python/typing/blob/master/docs/source/libraries.rst), which provides additional context.

Pyright offers a way to verify the completeness of type information within a "py.typed" library. When I run this command on `anyio`, it reports a type completeness score of 92.3%. That's an impressive score, higher than most "py.typed" libraries! Thank you for making this investment.

```
pyright --verifytypes anyio

<detailed errors omitted for brevity>

Symbols exported by "anyio": 379
  With known type: 350
  With partially unknown type: 29

Type completeness score: 92.3%
```

So, by addressing the remaining 29 partially-unknown types, you can hit 100% type completeness!

Here's the full list of partially-incomplete types:

```
anyio.maybe_async
  /anyio/_core/_compat.py:error: Type of parameter "__obj" is partially unknown
    Parameter type is "AnyDeprecatedAwaitable"
      Type argument 0 has unknown type
anyio._core._testing.TaskInfo.id
  /anyio/_core/_testing.py:23:14 - error: Type unknown for variable "anyio._core._testing.TaskInfo.id"
anyio._core._testing.TaskInfo.parent_id
  /anyio/_core/_testing.py:24:14 - error: Type unknown for variable "anyio._core._testing.TaskInfo.parent_id"
anyio._core._testing.TaskInfo.name
  /anyio/_core/_testing.py:25:14 - error: Type unknown for variable "anyio._core._testing.TaskInfo.name"
anyio._core._testing.TaskInfo.coro
  /anyio/_core/_testing.py:26:14 - error: Type unknown for variable "anyio._core._testing.TaskInfo.coro"
anyio._core._fileio.Path.__weakref__
  /anyio/_core/_fileio.py:235:26 - error: Type unknown for variable "anyio._core._fileio.Path.__weakref__"
anyio._core._tasks.FailAfterContextManager
  error: Type of base class "anyio._core._compat.DeprecatedAsyncContextManager" is partially unknown
    Type argument 0 has unknown type
anyio.key
  /anyio/__init__.py:110:5 - error: Type unknown for variable "anyio.key"
anyio.value
  /anyio/__init__.py:110:10 - error: Type unknown for variable "anyio.value"
anyio.abc.key
  /anyio/abc/__init__.py:31:5 - error: Type unknown for variable "anyio.abc.key"
anyio.abc.value
  /anyio/abc/__init__.py:31:10 - error: Type unknown for variable "anyio.abc.value"
anyio.lowlevel.RunvarToken.__init__
  /anyio/lowlevel.py:82:9 - error: Type of parameter "var" is partially unknown
    Parameter type is "RunVar[Unknown]"
      Type argument 0 has unknown type
anyio.streams.memory.MemoryObjectReceiveStream.clone
  /anyio/streams/memory.py:103:9 - error: Return type is partially unknown
    Return type is "MemoryObjectReceiveStream[Unknown]"
      Type argument 0 has unknown type
anyio.streams.memory.MemoryObjectSendStream.clone
  /anyio/streams/memory.py:207:9 - error: Return type is partially unknown
    Return type is "MemoryObjectSendStream[Unknown]"
      Type argument 0 has unknown type
anyio.streams.tls.TLSListener.listener
  /anyio/streams/tls.py:216:5 - error: Type argument 0 has unknown type
```

**Comment by agronholm** [comment] 2021-11-27 23:37
Thank you for taking the time to explain this. I'm reconsidering filling out the parameters explicitly if indeed typeshed follows this practice too.

**Comment by agronholm** [comment] 2021-11-28 00:06
Some of these errors make absolutely no sense. The ones in `_testing` are from `TaskInfo.__init__()` where initializer arguments are assigned to attributes. The arguments have explicit types defined so why is pyright complaining that their types are unknown??? If I do `self.id: int = id` it will shut up, but the type inference is pretty clear there so why is there an error at all?

**Comment by tkukushkin** [comment] 2021-11-28 00:11
This is explained there https://github.com/microsoft/pyright/issues/1846

**Comment by agronholm** [comment] 2021-11-28 00:20
It talks about heuristics on assignment, but if I directly assign the value of an annotated argument to an attribute, there shouldn't be any confusion about what the type should be. Maybe I'll read the post more carefully tomorrow and finish the adjustments. Currently sitting at 99.2% completeness.

**Comment by erictraut** [comment] 2021-11-28 00:34
Type inference rules are not governed by any specification (including PEP 484), and inference rules differ from one type checker to the next. It would be inadvisable to rely on type inference for symbols that comprise the public interface contract for your library.

There are situations that may seem obvious to you but are not obvious to a type checker's algorithms. We've talked about possibly exempting other specific cases such as a single unconditional assignment of an instance variable within an `__init__` method where the RHS of the assignment is an annotated input parameter, but such a specific case is difficult to describe and enforce.

It's great to hear that you've hit 99.5% type completeness! Let me know if there's anything I can do to help you cross the finish line.

**Comment by agronholm** [comment] 2021-11-28 00:36
There is one error that has me scratching my head:
```
anyio.maybe_async
  /home/alex/workspace/anyio/src/anyio/_core/_compat.py:error: Type of parameter "__obj" is partially unknown
    Parameter type is "AnyDeprecatedAwaitable"
      Type argument 0 has unknown type
```
I have no idea what that means.

**Comment by agronholm** [comment] 2021-11-28 00:39
Also this:
```
anyio._core._fileio.Path.__weakref__
  /home/alex/workspace/anyio/src/anyio/_core/_fileio.py:235:26 - error: Type unknown for variable "anyio._core._fileio.Path.__weakref__"
```
I have no clue how the `__weakref__` member is supposed to be annotated.

**Comment by tkukushkin** [comment] 2021-11-28 00:41
> There is one error that has me scratching my head:
> 
> ```
> anyio.maybe_async
>   /home/alex/workspace/anyio/src/anyio/_core/_compat.py:error: Type of parameter "__obj" is partially unknown
>     Parameter type is "AnyDeprecatedAwaitable"
>       Type argument 0 has unknown type
> ```
> 
> I have no idea what that means.

Try this:
```
 AnyDeprecatedAwaitable = Union['DeprecatedAwaitable', 'DeprecatedAwaitableFloat',
-                               'DeprecatedAwaitableList', TaskInfo]
+                               'DeprecatedAwaitableList[Any]', TaskInfo]
```

**Comment by erictraut** [comment] 2021-11-28 00:42
Yes, `AnyDeprecatedAwaitable` is a type alias that references `AnyDeprecatedAwaitable`. It's not clear whether the intent is for the type alias to also be generic or for the type alias to reference `AnyDeprecatedAwaitable[Any]`.

**Comment by agronholm** [comment] 2021-11-28 00:43
I used `DeprecatedAwaitableList[T]` and that worked. I could not have figured it out from that error message though! Thanks.
As for the weakref, I could just use `Any`, but is there a "proper" answer? I could not find anything relevant from typeshed. The actual type is `builtins.weakref` which cannot be referenced normally.

**Comment by erictraut** [comment] 2021-11-28 00:50
Yeah, I agree that `__weakref__` shouldn't require an explicit type annotation. I'll update pyright to special-case this along with several other dundered symbols whose types are well defined by the Python standard (e.g., `__doc__` and `__dict__`). you could use an explicit `Any` type annotation in the meantime if you'd like.

**Closed** 2021-11-28 20:39 UTC
